version: '3'

services:

  frontend:
    image: node
    container_name: frontend
    working_dir: /mosaicdl/frontend
    command: make dev
    volumes:
      - ../src/frontend:/mosaicdl/frontend
    ports:
      - 8080:8080

  backend:
    image: python
    container_name: backend
    working_dir: /mosaicdl/backend
    command: make dev
    volumes:
      - ../src/backend:/mosaicdl/backend
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.docker
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: mosaicdl
      MYSQL_ROOT_PASSWORD: root
